const logs = [
  {
    action: "Role change",
    detail: "Taylor Morgan granted HR Admin to Jordan Lee",
    time: "Apr 09, 2026 09:12",
  },
  {
    action: "SSO policy",
    detail: "Domain allowlist updated for corp.company.com",
    time: "Apr 08, 2026 16:44",
  },
  {
    action: "Export",
    detail: "Users export generated by Casey Patel",
    time: "Apr 07, 2026 11:03",
  },
];

const AuditLogs = () => {
  return (
    <section className="audit">
      <h1>System Audit Logs</h1>
      <div className="audit__list">
        {logs.map((log) => (
          <div key={log.detail} className="audit__item">
            <div className="audit__action">{log.action}</div>
            <div className="audit__detail">{log.detail}</div>
            <div className="audit__time">{log.time}</div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default AuditLogs;
